### ISSUE TITLE
Kernel upgrade fails

### ISSUE THREAD

**Issue by SziluChannel** [ParrotSec/parrot-core#14]
I have recently apt upgraded the system, however the automatic kernel installation failed, and thus the system is  unable to boot into the new version.

My setup:
MacBook Air 2012
Previous kernel version: 6.1.0-1
Parrot OS Home edition

Here is the log file:
[make.log](https://github.com/ParrotSec/parrot-core/files/13538511/make.log)

And here is the output of the failed install attempt:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up linux-headers-6.5.0-3parrot1-amd64 (6.5.3-3parrot1) ...
/etc/kernel/header_postinst.d/dkms:
dkms: running auto installation service for kernel 6.5.0-3parrot1-amd64.
Sign command: /lib/modules/6.5.0-3parrot1-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
'make' -j4 KVER=6.5.0-3parrot1-amd64 KSRC=/lib/modules/6.5.0-3parrot1-amd64/build.............(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.5.0-3parrot1-amd64 (x86_64)
Consult /var/lib/dkms/realtek-rtl8188eus/5.3.9~git20230101.f8ead57/build/make.lo
g for more information.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.5.0-3parrot1-amd64 failed!
run-parts: /etc/kernel/header_postinst.d/dkms exited with return code 11
Failed to process /etc/kernel/header_postinst.d at /var/lib/dpkg/info/linux-head
ers-6.5.0-3parrot1-amd64.postinst line 11.
dpkg: error processing package linux-headers-6.5.0-3parrot1-amd64 (--configure):
 installed linux-headers-6.5.0-3parrot1-amd64 package post-installation script s
ubprocess returned error exit status 1
dpkg: dependency problems prevent configuration of linux-headers-amd64:
 linux-headers-amd64 depends on linux-headers-6.5.0-3parrot1-amd64 (= 6.5.3-3par
rot1); however:
  Package linux-headers-6.5.0-3parrot1-amd64 is not configured yet.

dpkg: error processing package linux-headers-amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up linux-image-6.5.0-3parrot1-amd64 (6.5.3-3parrot1) ...
/etc/kernel/postinst.d/dkms:
dkms: running auto installation service for kernel 6.5.0-3parrot1-amd64.
Sign command: /lib/modules/6.5.0-3parrot1-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
'make' -j4 KVER=6.5.0-3parrot1-amd64 KSRC=/lib/modules/6.5.0-3parrot1-amd64/buil
d.............(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.5.0-3parrot1-amd64 (x86_64)
Consult /var/lib/dkms/realtek-rtl8188eus/5.3.9~git20230101.f8ead57/build/make.log for more information.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.5.0-3parrot1-amd64 failed!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
dpkg: error processing package linux-image-6.5.0-3parrot1-amd64 (--configure):
 installed linux-image-6.5.0-3parrot1-amd64 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of linux-image-amd64:
 linux-image-amd64 depends on linux-image-6.5.0-3parrot1-amd64 (= 6.5.3-3parrot1); however:
  Package linux-image-6.5.0-3parrot1-amd64 is not configured yet.

dpkg: error processing package linux-image-amd64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 linux-headers-6.5.0-3parrot1-amd64
 linux-headers-amd64
 linux-image-6.5.0-3parrot1-amd64
 linux-image-amd64
Scanning application launchers
Removing duplicate launchers or broken launchers
Launchers are updated
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by tissyp** [comment]
Hello. This is a known issue and we already came up with a solution. You can find it here https://pastebin.com/RrrWjTwdIl giorno 3 dic 2023, alle ore 10:50, SziluChannel ***@***.***> ha scritto:﻿
I have recently apt upgraded the system, however the automatic kernel installation failed, and thus the system is  unable to boot into the new version.
My setup:
MacBook Air 2012
Previous kernel version: 6.1.0-1
Parrot OS Home edition
Here is the log file:
make.log
And here is the output of the failed install attempt:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up linux-headers-6.5.0-3parrot1-amd64 (6.5.3-3parrot1) ...
/etc/kernel/header_postinst.d/dkms:
dkms: running auto installation service for kernel 6.5.0-3parrot1-amd64.
Sign command: /lib/modules/6.5.0-3parrot1-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
'make' -j4 KVER=6.5.0-3parrot1-amd64 KSRC=/lib/modules/6.5.0-3parrot1-amd64/build.............(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.5.0-3parrot1-amd64 (x86_64)
Consult /var/lib/dkms/realtek-rtl8188eus/5.3.9~git20230101.f8ead57/build/make.lo
g for more information.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.5.0-3parrot1-amd64 failed!
run-parts: /etc/kernel/header_postinst.d/dkms exited with return code 11
Failed to process /etc/kernel/header_postinst.d at /var/lib/dpkg/info/linux-head
ers-6.5.0-3parrot1-amd64.postinst line 11.
dpkg: error processing package linux-headers-6.5.0-3parrot1-amd64 (--configure):
 installed linux-headers-6.5.0-3parrot1-amd64 package post-installation script s
ubprocess returned error exit status 1
dpkg: dependency problems prevent configuration of linux-headers-amd64:
 linux-headers-amd64 depends on linux-headers-6.5.0-3parrot1-amd64 (= 6.5.3-3par
rot1); however:
  Package linux-headers-6.5.0-3parrot1-amd64 is not configured yet.

dpkg: error processing package linux-headers-amd64 (--configure):
 dependency problems - leaving unconfigured
Setting up linux-image-6.5.0-3parrot1-amd64 (6.5.3-3parrot1) ...
/etc/kernel/postinst.d/dkms:
dkms: running auto installation service for kernel 6.5.0-3parrot1-amd64.
Sign command: /lib/modules/6.5.0-3parrot1-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
'make' -j4 KVER=6.5.0-3parrot1-amd64 KSRC=/lib/modules/6.5.0-3parrot1-amd64/buil
d.............(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.5.0-3parrot1-amd64 (x86_64)
Consult /var/lib/dkms/realtek-rtl8188eus/5.3.9~git20230101.f8ead57/build/make.log for more information.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.5.0-3parrot1-amd64 failed!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
dpkg: error processing package linux-image-6.5.0-3parrot1-amd64 (--configure):
 installed linux-image-6.5.0-3parrot1-amd64 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of linux-image-amd64:
 linux-image-amd64 depends on linux-image-6.5.0-3parrot1-amd64 (= 6.5.3-3parrot1); however:
  Package linux-image-6.5.0-3parrot1-amd64 is not configured yet.

dpkg: error processing package linux-image-amd64 (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 linux-headers-6.5.0-3parrot1-amd64
 linux-headers-amd64
 linux-image-6.5.0-3parrot1-amd64
 linux-image-amd64
Scanning application launchers
Removing duplicate launchers or broken launchers
Launchers are updated
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by SziluChannel** [comment]
I did not intend to do that.
The link is not working.

**Comment by tissyp** [comment]
Does this work now?https://t.me/parrotsecgroup/1/540666Otherwise I’ll send you the complete solution here, the text is a bit longIl giorno 3 dic 2023, alle ore 11:59, SziluChannel ***@***.***> ha scritto:﻿
I did not intend to do that.
The link is not working.

**Comment by SziluChannel** [comment]
Thank you for the help, now it works!

Maybe this solution should be posted somewhere to help out others!
