### ISSUE TITLE
Nmap 7.93.+ - ms-sql issues

### ISSUE THREAD

**Issue by Schnugaf** [ParrotSec/parrot-core#16]
Hi,

Came across an issue with running nmap with ms-sql scripts.
It threw an error and after searching a bit I came across a similar error mentioned for Kali.
The issue was introduced in Nmap 7.93+ versions.

I manually made the changes that was added to the kali repo, and it appears to be working correctly after.
There are some wrong variable used in the lib and some typos that makes the ms-sql scripts fail.

See changes performed on kali repo here;
https://gitlab.com/kalilinux/packages/nmap/-/commit/984afc842c6e4a0b4f1b4c3fdd2ecaf10e7127c9

**Comment by PalinuroSec** [comment]
i am implementing the kali fix in nmap 7.94+git20230807.3be01efb1+dfsg-2+parrot1, which will be included by default in parrot 6.1 to be released soon
