### ISSUE TITLE
ARM version?

### ISSUE THREAD

**Issue by Hacksawfred3232** [ParrotSec/parrot-core#2]
I have a raspberry pi Laptop (And 2 spare WiFi dongles) that i want to use this OS on, is there anyway you can provide a ARM version of this? FYI here is the homepage for the raspberry pi:
https://www.raspberrypi.org/

**Comment by mibofra** [comment]
I've completed the image for the rapsberry pi2/3. A bit more and it will be released soon man.

**Comment by Hacksawfred3232** [comment]
Thanks for letting me know!
