### ISSUE TITLE
PS1 inconsistency

### ISSUE THREAD

**Issue by kurobeats** [ParrotSec/parrot-core#4]
On a failed command the prompt colour is malformed (white closed bracket instead of red). I've taken screenshots to show:
Normal:
![Screenshot from 2019-06-11 09-41-45](https://user-images.githubusercontent.com/4091936/59237505-298c7a80-8c2d-11e9-9ef1-fffbf5e805cb.png)
After command failed:
![Screenshot from 2019-06-11 09-41-14](https://user-images.githubusercontent.com/4091936/59237509-2db89800-8c2d-11e9-8312-9685847edd6d.png)

**Comment by PalinuroSec** [comment]
thanks for having reported that, we have to fix it within the next release.
Feel free t osend us a pull request if you want to help us.

**Comment by DanieleQ97** [comment]
Done... I think
Before fix:
![Before](https://user-images.githubusercontent.com/50218939/60390470-cda06d80-9ad7-11e9-88d8-d20f46bf3524.jpg)
After fix:
![After](https://user-images.githubusercontent.com/50218939/60390473-db55f300-9ad7-11e9-89bf-679bf2680bbb.jpg)

**Comment by kurobeats** [comment]
seems good to me

**Comment by PalinuroSec** [comment]
pull request accepted :)

**Comment by PalinuroSec** [comment]
it's too late to include it in parrot 4.7, but the change will automatically enter 4.8 and later (including the experimental 5.x branch we are working on right now) in the next days
